[{:name=>"Harriet Emily Malin",
  :relation_level=>2,
  :gender=>"Female",
  :birth_place=>"Rockport Twp, Summit, Utah, United States",
  :birth_year=>1873,
  :image_note_urls=>[],
  :afn=>"KWQC-VT5"},
 {:name=>"John McGuikin Malin",
  :relation_level=>3,
  :gender=>"Male",
  :birth_place=>"Chester, Pennsylvania, United States",
  :birth_year=>1833,
  :image_note_urls=>[],
  :afn=>"KWQC-VY3"},
 {:name=>"Paul Malin Pack",
  :relation_level=>1,
  :gender=>"Male",
  :birth_place=>"Kamas, Summit, Utah, United States",
  :birth_year=>1907,
  :image_note_urls=>[],
  :afn=>"KWQC-VTT"},
 {:name=>"API User 3075",
  :relation_level=>0,
  :gender=>"Male",
  :birth_place=>"Utah, United States",
  :birth_year=>1950,
  :image_note_urls=>
   ["http://dl.dropbox.com/u/40012820/kids.jpg",
    "http://dl.dropbox.com/u/40012820/johnpack1.jpg"],
  :afn=>"KW3B-NFH"},
 {:name=>"Don Elbert Pack",
  :relation_level=>2,
  :gender=>"Male",
  :birth_place=>"Salt Lake City, Salt Lake, Utah, United States",
  :birth_year=>1873,
  :image_note_urls=>["http://dl.dropbox.com/u/40012820/johnpack1.jpg"],
  :afn=>"KWQC-VTP"},
]